### ISSUE TITLE
vite로 react-typescript app을 생성한다.

### ISSUE THREAD

**Issue by ohs8283** [code-of-potatoes/todo-list#1]
---
name: issue template
about: 이슈 템플릿입니다.
title: ''
labels: ''
assignees: m1nsuppp

---

## 이슈 내용

tolist프로젝트를 개발하기 위해 라이브러리로 react와 언어는 TypeScript를 사용할 것 입니다. 

## 상세 내용

패키지 매니저로는 yarn을 이용 할 것입니다

## 우선 순위

높음

**Comment by m1nsuppp** [comment]
- `react`는 프레임워크가 아닙니다

**Comment by ohs8283** [comment]
1. yarn creat vite 로 vite를 설치한후
2. git파일과 같이 들어갈수있도록 옮겨 놓고
3. yarn install 를 실행해 node_modules를 설치 했습니다
4. 확인차로 yarn vite를 실행해 프로그램이 제대로 돌아가는지 확인했습니다
